export const NOTIFICATION_TYPES = {
  // Order Lifecycle
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_ACCEPTED: "ORDER_ACCEPTED",
  ORDER_REJECTED: "ORDER_REJECTED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  FOOD_PREPARING: "FOOD_PREPARING",
  FOOD_READY: "FOOD_READY",
  DELIVERY_PARTNER_ASSIGNED: "DELIVERY_PARTNER_ASSIGNED",
  ORDER_PICKED_UP: "ORDER_PICKED_UP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERY_PARTNER_NEARBY: "DELIVERY_PARTNER_NEARBY",
  DELIVERY_DELAYED: "DELIVERY_DELAYED",
  ORDER_DELIVERED: "ORDER_DELIVERED",

  // Payments & Refunds
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_PROCESSED: "REFUND_PROCESSED",

  // Delivery Partner Specific
  NEW_DELIVERY_REQUEST: "NEW_DELIVERY_REQUEST",
  DELIVERY_ACCEPTED: "DELIVERY_ACCEPTED",
  DELIVERY_CANCELLED: "DELIVERY_CANCELLED",
  EARNINGS_UPDATED: "EARNINGS_UPDATED",

  // Restaurant Specific
  NEW_ORDER: "NEW_ORDER",
  ORDER_MODIFIED: "ORDER_MODIFIED",
  IMPORTANT_ORDER_ALERT: "IMPORTANT_ORDER_ALERT",

  // Marketing & Engagement
  CART_REMINDER: "CART_REMINDER",
  REVIEW_REMINDER: "REVIEW_REMINDER",
  COUPON: "COUPON",
  PROMOTION: "PROMOTION",
  SPECIAL_OFFER: "SPECIAL_OFFER",

  // Account & Security
  ACCOUNT_UPDATE: "ACCOUNT_UPDATE",
  SECURITY_ALERT: "SECURITY_ALERT",
};

export const NOTIFICATION_PRIORITIES = {
  HIGH: "HIGH",
  NORMAL: "NORMAL",
  LOW: "LOW",
};

export const NOTIFICATION_CHANNELS = {
  IN_APP: "IN_APP",
  WEBSOCKET: "WEBSOCKET",
  PUSH: "PUSH",
  SMS: "SMS",
};

export const RECIPIENT_TYPES = {
  CUSTOMER: "CUSTOMER",
  USER: "USER",
  RESTAURANT: "RESTAURANT",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
};

export const NOTIFICATION_PRIORITY_MAP = {
  [NOTIFICATION_TYPES.PAYMENT_FAILED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_TYPES.ORDER_CANCELLED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_TYPES.DELIVERY_PARTNER_NEARBY]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_TYPES.SECURITY_ALERT]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_TYPES.NEW_DELIVERY_REQUEST]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_TYPES.NEW_ORDER]: NOTIFICATION_PRIORITIES.HIGH,

  [NOTIFICATION_TYPES.ORDER_PLACED]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.PAYMENT_SUCCESS]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.ORDER_ACCEPTED]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.FOOD_PREPARING]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.FOOD_READY]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.DELIVERY_PARTNER_ASSIGNED]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.ORDER_PICKED_UP]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.OUT_FOR_DELIVERY]: NOTIFICATION_PRIORITIES.NORMAL,
  [NOTIFICATION_TYPES.ORDER_DELIVERED]: NOTIFICATION_PRIORITIES.NORMAL,

  [NOTIFICATION_TYPES.PROMOTION]: NOTIFICATION_PRIORITIES.LOW,
  [NOTIFICATION_TYPES.COUPON]: NOTIFICATION_PRIORITIES.LOW,
  [NOTIFICATION_TYPES.CART_REMINDER]: NOTIFICATION_PRIORITIES.LOW,
  [NOTIFICATION_TYPES.REVIEW_REMINDER]: NOTIFICATION_PRIORITIES.LOW,
};
